version: "3.7"

services: 
 satdress:
    build: . 
    container_name: satdress
    environment:
      - PORT=17422
      - DOMAIN=localhost
      - SECRET=askdbasjdhvakjvsdjasd
      - SITE_OWNER_URL=https://x.com/topnotch
      - SITE_OWNER_NAME=@TooShort
      - SITE_NAME=TopNotch
    ports:
      - 17422:17422
    volumes:
      - satdress-data:/topnotch.net

volumes:
  satdress-data:
    name: satdress-data

